# Use the official Python 3.10 image as the base image
# The python:3.10-slim base image is a lightweight version of Python, ideal for production and development environments with minimal overhead.
FROM python:3.10-slim

# Set the working directory in the container
# This ensures all commands and file paths are relative to /app in the container
WORKDIR /app

# Copy the entire project directory into the container
# Copies your entire project directory into the container's /app directory.
COPY . /app

# Install required system packages
RUN apt-get update && apt-get install -y \
    libaio1 \
    build-essential \
    wget \
    unzip

# Download and install the Oracle Instant Client
RUN wget https://download.oracle.com/otn_software/linux/instantclient/2360000/instantclient-basiclite-linux.x64-23.6.0.24.10.zip && \
    unzip instantclient-basiclite-linux.x64-23.6.0.24.10.zip -d /opt/oracle && \
    rm -f instantclient-basiclite-linux.x64-23.6.0.24.10.zip
    
# Set environment variables for Oracle Instant Client
ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_23_6:$LD_LIBRARY_PATH
ENV PATH=/opt/oracle/instantclient_23_6:$PATH    

# Copy the requirements file into the container
COPY requirements.txt ./

# Install Python dependencies
# Installs the required Python packages from the requirements.txt file. The --no-cache-dir option avoids caching, reducing image size.
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project files into the container
COPY . .

# Set environment variables for Python (optional but recommended)
# PYTHONDONTWRITEBYTECODE=1: Prevents .pyc files from being written to disk, keeping the container clean.
# PYTHONUNBUFFERED=1: Ensures output is logged in real-time rather than being buffered.
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV GOOGLE_APPLICATION_CREDENTIALS="/app/config/bigquery_service_account.json"

# Add src directory to PYTHONPATH
ENV PYTHONPATH=/app

# Default command to run the application
# Specifies the script to run (src/data_generator.py) as the default command when the container starts.
#CMD ["python", "src/data_generator.py"]
CMD ["python", "src/test_oracle_connection.py"]
